-- MySQL Script generated by MySQL Workbench
-- Mon Jul 14 10:22:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema perfilApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema perfilApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perfilApp` DEFAULT CHARACTER SET utf8 ;
USE `perfilApp` ;

-- -----------------------------------------------------
-- Table `perfilApp`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfilApp`.`rol` (
  `idrol` INT NOT NULL,
  `nomRol` VARCHAR(45) NOT NULL,
  `estadoRol` INT NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perfilApp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfilApp`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `rol_idrol`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `perfilApp`.`rol` (`idrol`)
    ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- -----------------------------------------------------
-- Table `perfilApp`.`infApp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfilApp`.`infApp` (
  `idinfApp` INT NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `ultActualizacion` DATE NOT NULL,
  `desarrollador` VARCHAR(45) NOT NULL,
  `proveedor` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `almacenamiento` DECIMAL(10,2) NOT NULL,
  `enlaceManual` VARCHAR(200) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idinfApp`, `usuario_idusuario`),
  CONSTRAINT `fk_infApp_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `perfilApp`.`usuario` (`idusuario`)
    ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- -----------------------------------------------------
-- Table `perfilApp`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfilApp`.`catalogo` (
  `idcatalogo` INT NOT NULL,
  `nomApp` VARCHAR(60) NOT NULL,
  `funcionApp` VARCHAR(50) NOT NULL,
  `tipoApp` VARCHAR(50) NOT NULL,
  `negoApp` VARCHAR(30) NOT NULL,
  `infApp_idinfApp` INT NOT NULL,
  PRIMARY KEY (`idcatalogo`),
  CONSTRAINT `fk_catalogo_infApp`
    FOREIGN KEY (`infApp_idinfApp`)
    REFERENCES `perfilApp`.`infApp` (`idinfApp`)
    ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
